name: Generate Commit Snake

on:
    schedule: 
        - cron: "0 0 * * *"
    workflow_dispatch: 

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
            - name: generate-snake
              uses: Platane/snk/svg-only@v2
              with: 
                    github_user_name: ${{ github.repository_owner }}
                    outputs: |
                        ./snakes/dark.svg?palette=github-dark&&color_snake=blue
                        ./snakes/light.svg?color_snake=#7845ab
                        ./snakes/ocean.svg?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
            - name: generate-lastfm-history
              uses: melipass/lastfm-to-markdown@v1.3.1
              with: 
                LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
                LASTFM_USER: ${{ secrets.LASTFM_USER }}
                INCLUDE_LINK: true
                IMAGE_COUNT: 5
            - name: commit-and-push
              uses: stefanzweifel/git-auto-commit-action@v4
              with: 
                    commit_message: Update Data
